name: CI for helloworld

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: 
        pip install flake8 pytest pytest-cov
        
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: isaiahlowjung/HelloWorld
