name: CI for helloworld

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov
        
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: isaiahlowjung/HelloWorld
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: lowkh2/DevOpsQARepo
        path: tests
        token: ${{secrets.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}}
    - name: Linter check with 
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 
    - name: Begin Pytest
      run: |
        mv ./tests/*.* ./
        pytest --cov
    - if: ${{failure()}}
      name: Create Issues
      uses: nashmaniac/create-issuep-action@v1.1
      with:
          title: Build Failed
          token: ${{}}
          assignees: ${{}}
          labels: workflow-failed
          body: Workflow failed for commit ${{}} @ ${{}}
          
    - name: Publish Unit Test Resuls
      uses: EnricoMi/publish-unit-test-result-action@v1.24
      
