name: CI for helloworld

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Libraries
      run: 
        pip install flake8 pytest pytest-cov
        
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: isaiahlowjung/HelloWorld
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: 3thannn/DevOpsQA
        path: tests
        tokens: ${{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}}

    - name: Begin Pytest
      run:
        mv ./tests/*.* ./
        pytest --cov
